### ISSUE TITLE
Does not work inside workspaces

### ISSUE THREAD

**Issue by PepijnSenders** [airbnb/ts-migrate#12]
```$ /Users/psenders/Documents/code/design-system-web/node_modules/.bin/ts-migrate init .
/bin/sh: /Users/psenders/Documents/code/design-system-web/packages/components/node_modules/.bin/tsc: No such file or directory
/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: $(npm bin)/tsc --init
/bin/sh: /Users/psenders/Documents/code/design-system-web/packages/components/node_modules/.bin/tsc: No such file or directory

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.init [as default] (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/build/commands/init.js:27:25)
    at Object.handler (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/build/cli.js:20:19)
    at Object.runCommand (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.<anonymous> (/Users/psenders/Documents/code/design-system-web/node_modules/ts-migrate/build/cli.js:146:29)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
  status: 127,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(127) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,  58,  32,  47,  85, 115,
      101, 114, 115,  47, 112, 115, 101, 110, 100, 101, 114, 115,
       47,  68, 111,  99, 117, 109, 101, 110, 116, 115,  47,  99,
      111, 100, 101,  47, 100, 101, 115, 105, 103, 110,  45, 115,
      121, 115, 116, 101, 109,  45, 119, 101,  98,  47, 112,  97,
       99, 107,  97, 103, 101, 115,  47,  99, 111, 109, 112, 111,
      110, 101, 110, 116, 115,  47, 110, 111, 100, 101,  95, 109,
      111, 100, 117, 108, 101, 115,  47,  46,  98, 105, 110,  47,
      116, 115,  99,  58,
      ... 27 more items
    ]
  ],
  pid: 20090,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(127) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,  58,  32,  47,  85, 115,
    101, 114, 115,  47, 112, 115, 101, 110, 100, 101, 114, 115,
     47,  68, 111,  99, 117, 109, 101, 110, 116, 115,  47,  99,
    111, 100, 101,  47, 100, 101, 115, 105, 103, 110,  45, 115,
    121, 115, 116, 101, 109,  45, 119, 101,  98,  47, 112,  97,
     99, 107,  97, 103, 101, 115,  47,  99, 111, 109, 112, 111,
    110, 101, 110, 116, 115,  47, 110, 111, 100, 101,  95, 109,
    111, 100, 117, 108, 101, 115,  47,  46,  98, 105, 110,  47,
    116, 115,  99,  58,
    ... 27 more items
  ]
}
error Command failed with exit code 1.```

**Comment by Rudeg** [comment]
Probably you don't have a typescript as a dependency, or it has a different path.
You need to install typescript as a dependency first or specify a correct path to the `node_modules/.bin/tsc`. Then, rerun ts-migrate.
