### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...rs":">=0.6.2","esprim'

### ISSUE THREAD

**Issue by liby** [airbnb/ts-migrate#141]
<details>
<summary>Console output</summary>

```
❯ yarn add --dev ts-migrate
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
warning ts-migrate > json5-writer > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning ts-migrate > json5-writer > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
error Received malformed response from registry for "ajv". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Received malformed response from registry for "ajv". The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:50508:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:5301:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:307:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:50550:19)
❯ yarn add --dev ts-migrate
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
warning ts-migrate > json5-writer > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning ts-migrate > json5-writer > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 131 new dependencies.
info Direct dependencies
└─ ts-migrate@0.1.22
info All dependencies
├─ @babel/plugin-syntax-flow@7.14.5
├─ @babel/plugin-syntax-typescript@7.14.5
├─ @babel/plugin-transform-flow-strip-types@7.14.5
├─ @babel/plugin-transform-typescript@7.15.4
├─ @babel/preset-flow@7.14.5
├─ @babel/preset-typescript@7.15.0
├─ @babel/register@7.15.3
├─ @eslint/eslintrc@0.4.3
├─ @humanwhocodes/config-array@0.5.0
├─ @humanwhocodes/object-schema@1.2.0
├─ @ts-morph/bootstrap@0.9.1
├─ @ts-morph/common@0.9.2
├─ acorn-jsx@5.3.2
├─ acorn@7.4.1
├─ ansi-colors@4.1.1
├─ ansi-escapes@3.2.0
├─ ansi-regex@5.0.0
├─ argparse@1.0.10
├─ arr-flatten@1.1.0
├─ assign-symbols@1.0.0
├─ ast-types@0.11.7
├─ astral-regex@2.0.0
├─ atob@2.1.2
├─ base@0.11.2
├─ cache-base@1.0.1
├─ callsites@3.1.0
├─ camelcase@5.3.1
├─ class-utils@0.3.6
├─ cli-cursor@2.1.0
├─ cliui@6.0.0
├─ collection-visit@1.0.0
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ copy-descriptor@0.1.1
├─ create-jest-runner@0.5.3
├─ decode-uri-component@0.2.0
├─ deep-is@0.1.3
├─ doctrine@3.0.0
├─ emoji-regex@8.0.0
├─ enquirer@2.3.6
├─ eslint-utils@2.1.0
├─ eslint-visitor-keys@1.3.0
├─ eslint@7.32.0
├─ espree@7.3.1
├─ esprima@4.0.1
├─ esquery@1.4.0
├─ expand-brackets@2.1.4
├─ extglob@2.0.4
├─ fast-levenshtein@2.0.6
├─ figures@3.2.0
├─ file-entry-cache@6.0.1
├─ flat-cache@3.0.4
├─ flatted@3.2.2
├─ for-in@1.0.2
├─ functional-red-black-tree@1.0.1
├─ get-caller-file@2.0.5
├─ get-value@2.0.6
├─ has-value@1.0.0
├─ import-fresh@3.3.0
├─ is-accessor-descriptor@1.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-windows@1.0.2
├─ jest-worker@24.9.0
├─ jscodeshift@0.6.4
├─ json-schema@0.3.0
├─ json-stable-stringify-without-jsonify@1.0.1
├─ json5-writer@0.1.8
├─ lodash.clonedeep@4.5.0
├─ lodash.merge@4.6.2
├─ lodash.truncate@4.4.2
├─ log-update@3.4.0
├─ lru-cache@6.0.0
├─ make-dir@2.1.0
├─ map-visit@1.0.0
├─ mixin-deep@1.3.2
├─ nanomatch@1.2.13
├─ natural-compare@1.4.0
├─ node-modules-regexp@1.0.0
├─ object-copy@0.1.0
├─ optionator@0.9.1
├─ parent-module@1.0.1
├─ parse-ms@2.1.0
├─ pascalcase@0.1.1
├─ path-browserify@1.0.1
├─ pify@4.0.1
├─ pirates@4.0.1
├─ posix-character-classes@0.1.1
├─ pretty-ms@7.0.1
├─ private@0.1.8
├─ progress@2.0.3
├─ recast@0.16.2
├─ regexpp@3.2.0
├─ repeat-element@1.1.4
├─ require-directory@2.1.1
├─ require-from-string@2.0.2
├─ require-main-filename@2.0.0
├─ resolve-url@0.2.1
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ set-blocking@2.0.0
├─ set-value@2.0.1
├─ slice-ansi@4.0.0
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.3
├─ source-map-url@0.4.1
├─ split-string@3.1.0
├─ sprintf-js@1.0.3
├─ static-extend@0.1.2
├─ strip-json-comments@3.1.1
├─ table@6.7.1
├─ temp@0.8.4
├─ text-table@0.2.0
├─ throat@4.1.0
├─ to-object-path@0.3.0
├─ ts-migrate-plugins@0.1.22
├─ ts-migrate@0.1.22
├─ type-check@0.4.0
├─ type-fest@0.20.2
├─ union-value@1.0.1
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ use@3.1.1
├─ which-module@2.0.0
├─ word-wrap@1.2.3
├─ wrap-ansi@5.1.0
├─ y18n@4.0.3
├─ yallist@4.0.0
├─ yargs-parser@18.1.3
└─ yargs@15.4.1
✨  Done in 34.61s.
❯ npx -p ts-migrate -c "ts-migrate-full ./"
npm ERR! Unexpected end of JSON input while parsing near '...rs":">=0.6.2","esprim'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-09-04T08_44_46_967Z-debug.log
Install for [ 'ts-migrate@latest' ] failed with code 1
```
</details>

**Comment by Rudeg** [comment]
Not sure what's the issue here, it would be hard to resolve without an example repo.
