### ISSUE TITLE
Can't run tests locally on linux

### ISSUE THREAD

**Issue by coderaiser** [airbnb/ts-migrate#30]
Just cloned and installed repository and want to run tests, but it fails. Could you please help me?

```sh
coderaiser@cloudcmd:~/ts-migrate$ yarn test
yarn run v1.21.1
$ lerna run test
lerna notice cli v3.22.1
lerna info Executing command in 3 packages: "yarn run test"
ts-migrate-server: $ jest --config jest-config.json
ts-migrate-server:   console.log
ts-migrate-server:     log.info: TypeScript version: 3.9.7
ts-migrate-server:       at Object.info (tests/test-utils.ts:89:13)
ts-migrate-server:   console.log
ts-migrate-server:     log.info: Initialized tsserver project in 459.423ms.
ts-migrate-server:       at Object.info (tests/test-utils.ts:89:13)
ts-migrate-server:   console.log
ts-migrate-server:     log.info: Start...
ts-migrate-server:       at Object.info (tests/test-utils.ts:89:13)
ts-migrate-server:   console.log
ts-migrate-server:     log.info: [test-plugin] Plugin 1 of 1. Start...
ts-migrate-server:       at Object.info (tests/test-utils.ts:89:13)
ts-migrate-server: FAIL tests/commands/migrate/migrate.test.ts (6.51 s)
ts-migrate-server:   migrate command
ts-migrate-server:     ✕ Migrates project (5082 ms)
ts-migrate-server:   ● migrate command › Migrates project
ts-migrate-server:     : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
ts-migrate-server:       24 |   });
ts-migrate-server:       25 | 
ts-migrate-server:     > 26 |   it('Migrates project', async () => {
ts-migrate-server:          |   ^
ts-migrate-server:       27 |     const inputDir = path.resolve(__dirname, 'input');
ts-migrate-server:       28 |     const outputDir = path.resolve(__dirname, 'output');
ts-migrate-server:       29 |     const configDir = path.resolve(__dirname, 'config');
ts-migrate-server:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
ts-migrate-server:       at Suite.<anonymous> (tests/commands/migrate/migrate.test.ts:26:3)
ts-migrate-server: Test Suites: 1 failed, 1 total
ts-migrate-server: Tests:       1 failed, 1 total
ts-migrate-server: Snapshots:   0 total
ts-migrate-server: Time:        6.595 s, estimated 7 s
ts-migrate-server: Ran all test suites.
ts-migrate-server: error Command failed with exit code 1.
ts-migrate-server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 1 in 'ts-migrate-server'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Rudeg** [comment]
@coderaiser are you running it on mac or windows? 
I just tried to clone the repo, and it seems working for me.

**Comment by coderaiser** [comment]
@Rudeg I did it on linux :). On mac everything works good.

**Comment by Rudeg** [comment]
@coderaiser Haven't tested it on linux :( Looks like a bug. Feel free to put a PR that improves support for linux. We'd be happy to review it!

**Comment by coderaiser** [comment]
Looks like this related to timeouts and weak iron on digital ocean droplet.

**Comment by koji** [comment]
`yarn test` works with Ubuntu 20.0.4 on Parallels desktop for mac.

**Comment by edsrzf** [comment]
Closing this since it was due to weak hardware rather than OS. I also extended the timeout of this test in #70 since it sometimes timed out in CI, so that should also help.
