### ISSUE TITLE
Errors parsing TypeScript config

### ISSUE THREAD

**Issue by caleb15** [airbnb/ts-migrate#35]
```
(fifteen5) caleb•~/Documents/fifteen5(dev⚡)» yarn ts-migrate -- migrate ff/static/modules                                   [18:50:11]
yarn run v1.22.5
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ /home/caleb/Documents/fifteen5/node_modules/.bin/ts-migrate migrate ff/static/modules
forkTSServer
Logs in /tmp/ts-migrate-log-NvUlBG
npm run ts-migrate -- migrate <folder>

Fix TypeScript errors, using codemods

Positionals:
  folder                                                     [string] [required]

Options:
  -h, --help  Show help                                                [boolean]

Error: Errors parsing TypeScript config: error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["ff/static/modules/**/*"]' and 'exclude' paths were '[]'.

    at Object.parseTSConfig (/home/caleb/Documents/fifteen5/node_modules/ts-migrate-server/build/src/migrate/ParseTSConfig.js:27:15)
    at Object.migrate (/home/caleb/Documents/fifteen5/node_modules/ts-migrate-server/build/src/migrate/index.js:15:41)
    at Object.handler (/home/caleb/Documents/fifteen5/node_modules/ts-migrate/build/cli.js:93:48)
    at Object.runCommand (/home/caleb/Documents/fifteen5/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/caleb/Documents/fifteen5/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/caleb/Documents/fifteen5/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.<anonymous> (/home/caleb/Documents/fifteen5/node_modules/ts-migrate/build/cli.js:146:29)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Typescript config:
```jsonc
{
    "compilerOptions": {
      "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
      "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
      "allowJs": true,                       /* Allow javascript files to be compiled. */
      "jsx": "react",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
      "noEmit": true,                        /* Do not emit outputs. */
      "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
      "strict": true,                           /* Enable all strict type-checking options. */
      "baseUrl": "./ff/static/modules",         /* Base directory to resolve non-absolute module names. */
      "esModuleInterop": true,                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
      "forceConsistentCasingInFileNames": true  /* Casing matters in linux OS! */
    },
    "include": [
      "ff/static/modules/**/*"
    ]
  }
```

Rough tree of relevant directories:
```
.

├── ff
│   ├── other folders
│   ├── static
│   │   ├── other folders
│   │   ├── modules
│   │   │   ├── module subfolders w/ partially migrated typescript files. This is what I want to run ts-migrate against
```

I tried adding a `rootdir` of ./ and `./ff/static/modules` in my tsconfig but neither worked.

Note that I'm able to run `yarn tsc` without a TS18003 error

**Comment by caleb15** [comment]
I tried it on windows 10 w/ TS version 4.0.2, node 14, ts-migrate version 0.1.10, and I got a different error:

```
$ F:\fifteen5\node_modules\.bin\ts-migrate migrate ff/static/modules
TypeScript version: 4.0.2
npm run ts-migrate -- migrate [options] <folder>

Fix TypeScript errors, using codemods

Positionals:
  folder                                                                         [string] [required]

Options:
  -h, --help     Show help                                                                 [boolean]
  --sources, -s  Path to a subset of your project to rename (globs are ok).                 [string]

Examples:
  migrate /frontend/foo                               Migrate all the files in /frontend/foo
  npm run ts-migrate -- migrate /frontend/foo -s      Migrate all the files in /frontend/foo/bar,
  "bar/**/*" -s "node_modules/**/*.d.ts"              accounting for ambient types from
                                                      node_modules.

FileNotFoundError: File not found: F:/fifteen5/ff/static/modules/tsconfig.json
    at RealFileSystemHost.getFileNotFoundErrorIfNecessary (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:1107:50)
    at RealFileSystemHost.readFileSync (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:995:24)
    at TransactionalFileSystem.readFileSync (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:1584:32)
    at TsConfigResolver.getTsConfigFileJson (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2451:38)
    at TsConfigResolver.decorator (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2281:46)
    at TsConfigResolver.parseJsonConfigFileContent (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2447:59)
    at TsConfigResolver.decorator (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2281:46)
    at TsConfigResolver.getCompilerOptions (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2398:21)
    at TsConfigResolver.decorator (F:\fifteen5\node_modules\@ts-morph\common\dist\ts-morph-common.js:2281:46)
    at getTsConfigCompilerOptions (F:\fifteen5\node_modules\@ts-morph\bootstrap\dist\ts-morph-bootstrap.js:207:37) {
  path: 'F:/fifteen5/ff/static/modules/tsconfig.json',
  code: 'ENOENT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Now it looks like perhaps I was just using it incorrectly. I passed in . (current directory) and it worked! (Very slowly, but still!)

```
F:\fifteen5>yarn ts-migrate -- migrate .
yarn run v1.17.3
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ F:\fifteen5\node_modules\.bin\ts-migrate migrate .
TypeScript version: 4.0.2
Initialized tsserver project in 11306.893ms.
Start...
[strip-ts-ignore] Plugin 1 of 13. Start...
[strip-ts-ignore] Finished in 1721.592ms.
[hoist-class-statics] Plugin 2 of 13. Start...
[hoist-class-statics] Finished in 131.569ms.
[react-props] Plugin 3 of 13. Start...
[react-props] Finished in 1325.490ms.
[react-class-state] Plugin 4 of 13. Start...
[react-class-state] Finished in 29.595ms.
[react-class-lifecycle-methods] Plugin 5 of 13. Start...
[react-class-lifecycle-methods] Finished in 24.858ms.
[react-default-props] Plugin 6 of 13. Start...
[react-default-props] Finished in 16.059ms.
[react-shape] Plugin 7 of 13. Start...
[react-shape] Finished in 29.035ms.
[declare-missing-class-properties] Plugin 8 of 13. Start...
[declare-missing-class-properties] Finished in 433972.549ms.
[member-accessibility] Plugin 9 of 13. Start...
[member-accessibility] Finished in 87.888ms.
[explicit-any] Plugin 10 of 13. Start...
[explicit-any] Finished in 430783.822ms.
[eslint-fix] Plugin 11 of 13. Start...
The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.
The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.
The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.
[eslint-fix] Finished in 768580.781ms.
[ts-ignore] Plugin 12 of 13. Start...
[ts-ignore] Finished in 491808.940ms.
[eslint-fix] Plugin 13 of 13. Start...
The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.
[eslint-fix] Finished in 367601.743ms.
Finished in 2496130.800ms, for 13 plugin(s).
Writing 1568 updated file(s)...
Wrote 1568 updated file(s) in 365.166ms.
Done in 2510.79s.
```
