### ISSUE TITLE
Use tsconfig that's not at the root dir

### ISSUE THREAD

**Issue by NickHeiner** [airbnb/ts-migrate#92]
My package structure is:

```
tsconfig.json
packages/
  **/*.ts
```

I'd like to only transform the files under `packages`, but I want to use the `tsconfig.json` at the root. However, that doesn't appear to be an option. The tool looks for `packages/tsconfig.json`.

```
λ ts-migrate reignore ~/code/tvui/packages                                                                                                                                                                              
TypeScript version: 4.1.2
npm run ts-migrate -- reignore <folder>

Re-run ts-ignore on a project

Positionals:
  folder                                                                         [string] [required]

Options:
  -h, --help  Show help                                                                    [boolean]

FileNotFoundError: File not found: /Users/nheiner/code/tvui/packages/tsconfig.json
    at RealFileSystemHost.getFileNotFoundErrorIfNecessary (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:1113:50)
    at RealFileSystemHost.readFileSync (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:999:24)
    at TransactionalFileSystem.readFileSync (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:1590:32)
    at TsConfigResolver.getTsConfigFileJson (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2440:38)
    at TsConfigResolver.decorator (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2288:46)
    at TsConfigResolver.parseJsonConfigFileContent (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2436:59)
    at TsConfigResolver.decorator (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2288:46)
    at TsConfigResolver.getCompilerOptions (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2405:21)
    at TsConfigResolver.decorator (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/common/dist/ts-morph-common.js:2288:46)
    at getTsConfigCompilerOptions (/Users/nheiner/code/ts-migrate/node_modules/@ts-morph/bootstrap/dist/ts-morph-bootstrap.js:215:37) {
  path: '/Users/nheiner/code/tvui/packages/tsconfig.json',
  code: 'ENOENT'
}
```

I think a more robust algorithm would be to do a `find-up` from the passed `<folder>`.

**Comment by NickHeiner** [comment]
My workaround is to run `ts-migrate reignore` on the entire project, then use `git` to wipe away the unwanted changes.
